import './globals.css';
import type { Metadata } from 'next';
import { Inter } from 'next/font/google';
import classNames from 'classnames';
import { SWRProvider } from '@/app/swr-provider';

const inter = Inter({ subsets: ['latin'] });

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app'
};

export default function RootLayout({
  children
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body
        className={classNames(
          inter.className,
          'fixed w-full h-full select-none p-3'
        )}
      >
        <SWRProvider>
          <section className="full h-full mx-auto">{children}</section>
        </SWRProvider>
      </body>
    </html>
  );
}
